Repository roadrunner-php/jobs, pull requests merged in 2023-03, with the labels that each got.

#42 Update AMQPCreateInfo
  src/Queue/AMQPCreateInfo.php
Labels: bug

#44 Adds consume_all option to the AMQPCreateInfo DTO
  src/Queue/AMQPCreateInfo.php
Labels: bug, enhancement

#45 Starting from v2023.1.0, RR requires a queue name (if the consumer is used) or/and routing key for the push operations.
  src/Queue/AMQPCreateInfo.php
Labels: enhancement

#47 Remove built-in serializer
  src/Consumer.php
  src/Jobs.php
  src/Queue.php
  src/Queue/Pipeline.php
  src/QueueInterface.php
  src/Serializer/JsonSerializer.php
  src/Serializer/SerializerAwareInterface.php
  src/Serializer/SerializerInterface.php
  src/Task/PreparedTask.php
  src/Task/PreparedTaskInterface.php
  src/Task/QueuedTask.php
  src/Task/ReceivedTask.php
  src/Task/Task.php
  src/Task/TaskInterface.php
  tests/Unit/ConsumerTest.php
  tests/Unit/OptionsFactoryTest.php
  tests/Unit/PipelineTest.php
  tests/Unit/Queue/AMQPCreateInfoTest.php
  tests/Unit/Queue/BeanstalkCreateInfoTest.php
  tests/Unit/Queue/BoltdbCreateInfoTest.php
  tests/Unit/Queue/CreateInfoTest.php
  tests/Unit/Queue/MemoryCreateInfoTest.php
  tests/Unit/Queue/NatsCreateInfoTest.php
  tests/Unit/Queue/SQSCreateInfoTest.php
  tests/Unit/QueueTest.php
  tests/Unit/Task/PreparedTaskTest.php
  tests/Unit/Task/QueuedTaskTest.php
  tests/Unit/TaskCreationTest.php
Labels: enhancement

#51 Create Kafka driver create info
  .styleci.yml
  README.md
  src/Consumer.php
  src/Jobs.php
  src/KafkaOptions.php
  src/KafkaOptionsInterface.php
  src/Options.php
  src/Queue.php
  src/Queue/AMQPCreateInfo.php
  src/Queue/BeanstalkCreateInfo.php
  src/Queue/BoltdbCreateInfo.php
  src/Queue/CreateInfo.php
  src/Queue/CreateInfoInterface.php
  src/Queue/Kafka/Acks.php
  src/Queue/Kafka/CompressionCodec.php
  src/Queue/Kafka/ConsumePartition.php
  src/Queue/Kafka/ConsumerGroupOptions.php
  src/Queue/Kafka/ConsumerOffset.php
  src/Queue/Kafka/ConsumerOptions.php
  src/Queue/Kafka/OffsetType.php
  src/Queue/Kafka/PartitionOffset.php
  src/Queue/Kafka/ProducerOptions.php
  src/Queue/Kafka/RequiredAcks.php
  src/Queue/KafkaCreateInfo.php
  src/Queue/MemoryCreateInfo.php
  src/Queue/NatsCreateInfo.php
  src/Queue/Pipeline.php
  src/Queue/SQSCreateInfo.php
  src/QueueInterface.php
  src/Task/Factory/ReceivedTaskFactory.php
  src/Task/HeadersTrait.php
  src/Task/PreparedTask.php
  src/Task/QueuedTask.php
  src/Task/ReceivedTask.php
  src/Task/Task.php
  src/Task/WritableHeadersTrait.php
  tests/Unit/BaseTest.php
  tests/Unit/ConsumerTest.php
  tests/Unit/JobsTest.php
  tests/Unit/KafkaOptionsTest.php
  tests/Unit/OptionsFactoryTest.php
  tests/Unit/OptionsTest.php
  tests/Unit/PipelineTest.php
  tests/Unit/Queue/CreateInfoTest.php
  tests/Unit/Queue/Kafka/ConsumePartitionTest.php
  tests/Unit/Queue/Kafka/ConsumerGroupOptionsTest.php
  tests/Unit/Queue/Kafka/ConsumerOffsetTest.php
  tests/Unit/Queue/Kafka/ConsumerOptionsTest.php
  tests/Unit/Queue/Kafka/ProducerOptionsTest.php
  tests/Unit/Queue/KafkaCreateInfoTest.php
  tests/Unit/Queue/SQSCreateInfoTest.php
  tests/Unit/QueueTest.php
  tests/Unit/Stub/RPCConnectionStub.php
  tests/Unit/Task/Factory/ReceivedTaskFactoryTest.php
  tests/Unit/Task/HeadersTraitTest.php
  tests/Unit/Task/KafkaReceivedTaskTest.php
  tests/Unit/Task/PreparedTaskTest.php
  tests/Unit/Task/ReceivedTaskTest.php
  tests/Unit/TaskCreationTest.php
Labels: enhancement

#52 Adds backward compatibility for RR 2.x
  src/Task/Factory/ReceivedTaskFactory.php
Labels: enhancement
